# frozen_string_literal: true

source "https://rubygems.org"
# gemspec

gem "bulma-clean-theme"
gem 'bootstrap-sass', '~> 3.4.1'

group :jekyll_plugins do
    gem "jekyll-sitemap"
    gem "jekyll-seo-tag"
end

