language: python
matrix:
  include:
  - os: linux
    sudo: required
    python: 3.7
  - os: linux
    sudo: required
    python: 3.8

install: pip install -r requirements.txt
script: pytest --cov=pkdb_analysis
after_success: pip install codecov; codecov

cache:
  directories:
  - "$HOME/.cache/pip"

