""" Data types of pkdata tables"""
from typing import List

INT_MINUS_1 = "int_minus_1"
DATE_DTYPE = "datetime64[ns]"
NULLABLE_INT = "Int64"
STUDIES_DTYPES = {
    "sid": str,
    "licence": str,
    "access": str,
    "date": str,  # todo:  date dtype
    "creator": str,
    "curators": List[str],
    "substances": List[str],
    "reference_pmid": NULLABLE_INT,
    "reference_title": str,
    "reference_date": str,  # todo:  date dtype
}
INTERVENTION_DTYPES = {
    "intervention_pk": int,
    "study_sid": str,
    "study_name": str,
    "raw_pk": int,
    "normed": bool,
    "name": str,
    "route": str,
    "route_label": str,
    "form": str,
    "form_label": str,
    "application": str,
    "application_label": str,
    "time": str,  # has a string pattern which describes mutlitple dosing.
    "time_end": float,
    "time_unit": str,
    "measurement_type": str,
    "measurement_type_label": str,
    "calculation_type": str,
    "calculation_type_label": str,
    "choice": str,
    "choice_label": str,
    "substance": str,
    "substance_label": str,
    "value": float,
    "mean": float,
    "median": float,
    "min": float,
    "max": float,
    "sd": float,
    "se": float,
    "cv": float,
}
GROUP_DTYPES = {
    "study_name": str,
    "study_sid": str,
    "measurement_type": str,
    "group_count": int,
    "group_name": str,
    "substance": str,
    "count": int,
    "calculation_type": str,
    "group_parent_pk": INT_MINUS_1,
    "sd": float,
    "unit": str,
    "se": float,
    "min": float,
    "max": float,
    "cv": float,
    "median": float,
    "group_pk": float,
    "characteristica_pk": float,
    "mean": float,
    "choice": str,
    "value": float,
}
INDIVIDUAL_DTYPES = {
    "study_name": str,
    "study_sid": str,
    "measurement_type": str,
    "substance": str,
    "count": int,
    "individual_name": str,
    "individual_pk": int,
    "calculation_type": str,
    "individual_group_pk": int,
    "sd": float,
    "unit": str,
    "se": float,
    "min": float,
    "max": float,
    "cv": float,
    "median": float,
    "characteristica_pk": int,
    "mean": float,
    "choice": str,
    "value": float,
}
OUTPUT_DTYPES = {
    "study_sid": str,
    "study_name": str,
    "output_pk": int,
    "group_pk": INT_MINUS_1,
    "individual_pk": INT_MINUS_1,
    "intervention_pk": int,
    "measurement_type": str,
    "tissue": str,
    "calculation_type": str,
    "time_unit": str,
    "normed": bool,
    "calculated": bool,
    "output_type": str,
    "method": str,
    "substance": str,
    "label": str,
    "choice": str,
    "unit": str,
    "value": float,
    "median": float,
    "mean": float,
    "sd": float,
    "se": float,
    "cv": float,
    "min": float,
    "max": float,
    "time": float,
}
TIMECOURSE_DTYPES = {
    "study_sid": str,
    "study_name": str,
    "subset_pk": int,
    "subset_name": str,
    "group_pk": INT_MINUS_1,
    "individual_pk": INT_MINUS_1,
    "intervention_pk": List[int],
    "normed": bool,
    "tissue": str,
    "tissue_label": str,
    "method": str,
    "method_label": str,
    "label": str,
    "time_unit": str,
    "measurement_type": str,
    "measurement_type_label": str,
    "choice": str,
    "choice_label": str,
    "substance": str,
    "substance_label": str,
    "unit": str,
    "output_pk": List[int],
    "time": List[float],
    "value": List[float],
    "mean": List[float],
    "median": List[float],
    "min": List[float],
    "max": List[float],
    "sd": List[float],
    "se": List[float],
    "cv": List[float],
}
# SCATTER_DTYPES = {
#     "study_sid": str,
#     "study_name": str,
#     "subset_pk": int,
#     "subset_name": str,
#     "x_outputs_pk": List[int],
#     "x_intervention_pk": List[int],
#     "x_group_pk": List[int],
#     "x_individual_pk": List[int],
#     "x_normed": str,
#     "x_calculated": str,
#     "x_tissue": str,
#     "x_tissue_label": str,
#     "x_method": str,
#     "x_method_label": str,
#     "x_label": str,
#     "x_output_type": str,
#     "x_time": List[float],
#     "x_time_unit": str,
#     "x_measurement_type": str,
#     "x_measurement_type__label": str,
#     "x_choice": str,
#     "x_choice_label": str,
#     "x_substance": str,
#     "x_substance_label": str,
#     "x_value": List[float],
#     "x_mean": List[float],
#     "x_median": List[float],
#     "x_min": List[float],
#     "x_max": List[float],
#     "x_sd": List[float],
#     "x_se": List[float],
#     "x_cv": List[float],
#     "x_unit": str,
#     "x_dimension": int,
#     "x_data_point": List[int],
#     "y_outputs_pk": List[int],
#     "y_intervention_pk": str,
#     "y_group_pk": str,
#     "y_individual_pk": str,
#     "y_normed": str,
#     "y_calculated": str,
#     "y_tissue": str,
#     "y_tissue_label": str,
#     "y_method": str,
#     "y_method_label": str,
#     "y_label": str,
#     "y_output_type": str,
#     "y_time": str,
#     "y_time_unit": str,
#     "y_measurement_type": str,
#     "y_measurement_type__label": str,
#     "y_choice": str,
#     "y_choice_label": str,
#     "y_substance": str,
#     "y_substance_label": str,
#     "y_value": str,
#     "y_mean": str,
#     "y_median": str,
#     "y_min": str,
#     "y_max": str,
#     "y_sd": str,
#     "y_se": str,
#     "y_cv": str,
#     "y_unit": str,
#     "y_dimension": str,
#     "y_data_point": str,
# }

DTYPES = {
    "studies": STUDIES_DTYPES,
    "individuals": INDIVIDUAL_DTYPES,
    "groups": GROUP_DTYPES,
    "interventions": INTERVENTION_DTYPES,
    "outputs": OUTPUT_DTYPES,
    "timecourses": TIMECOURSE_DTYPES,
    "scatters": {},

    # "scatters": SCATTER_DTYPES,
}
