version: "3"
services:
  jekyll:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
    ports:
      - "4321:4000"
      - "35800:35729"
      - "3211:3000"
    networks:
      - default
